on:
  # keeping it here for a now to make sure things work
  # push:
  #   branches:
  #     - "main"
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [released]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: Push
        run: dotnet nuget push Ares.Datamodel.${VERSION}.nupkg \
          --api-key ${NUGET_TOKEN} \
          --source https://api.nuget.org/v3/index.json \
          --skip-duplicate
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
